- .husky/commit-msg
- .husky/pre-commit
- .prettierignore
- README.md
- apps/app/.eslintrc.json
- apps/app/src/app/app.component.spec.ts
- apps/app/src/app/app.component.ts
- apps/app/src/index.html
- commitlint.config.js
- decorate-angular-cli.js
- package-lock.json
- package.json
- build: add husky and lint-staged
- build: configure lint-staged
- build: fix hooks
- build: fix lint-staged
- build(commitlint): add commit-msg
> Add commit-msg and pre-commit with husky

- .github/workflows/ci-apps-app.yml
- .github/workflows/ci-libs-ui.yaml
Create a new action to lint and test ui (libs)
Rename and add test to action app (apps) (from ci-angular to ci-apps-app)
> Add action for lint and test ui

- apps/app/src/app/modules/pages/modules/applications/applications.module.ts
- apps/app/src/app/modules/pages/modules/dashboard/dashboard.component.ts
- apps/app/src/app/modules/pages/modules/sessions/sessions.component.ts
- apps/app/src/app/modules/pages/pages.component.html
- feat(title): update title using translation
- feat(header): update app name
> Update title using tranlate service

- app.Dockerfile
- apps/app-e2e/src/integration/app.spec.ts
- apps/app-e2e/src/integration/applications.spec.ts
- apps/app-e2e/src/integration/dashboard.spec.ts
- apps/app-e2e/src/integration/sessions.spec.ts
- apps/app/src/app/app-routing.module.ts
- apps/app/src/app/app-translate.module.ts
- apps/app/src/app/app.module.ts
- apps/app/src/app/core/services/http/error.service.ts
- apps/app/src/app/pages/pages.component.html
- apps/app/src/app/pages/pages.component.ts
- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.html
- apps/app/src/app/pages/pages/dashboard/dashboard.component.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/pages/task-detail/task-detail.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.html
- apps/app/src/app/pages/pages/sessions/sessions.component.html
- apps/app/src/environments/environment.prod.ts
- apps/app/src/environments/environment.ts
https://github.com/aneoconsulting/ArmoniK/pull/337
> fix: update admin path

- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.html
- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
- apps/app/src/app/pages/pages/dashboard/dashboard.component.html
- apps/app/src/app/pages/pages/dashboard/dashboard.component.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
Fix an issue where the service called on the child component wasn't found (`settingsService`)
> fix: redirect seq link

- apps/api/src/app/modules/applications/applications.controller.ts
- apps/api/src/app/modules/applications/applications.service.ts
- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.html
- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.ts
- apps/app/src/app/pages/pages/dashboard/dashboard.component.spec.ts
- apps/app/src/app/pages/pages/dashboard/dashboard.component.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- libs/armonik-typing/src/lib/entities/application.entity.ts
Update errors table on dashbord with many new functionnalities
- Sort
- Filters
- Faster
> fix: errors table on dashboard

- apps/app/src/app/core/services/language.service.spec.ts
Doit être mergée en première parce que je crois qu'elle fix des erreurs dans les run de #198 et #195
> fix: update tests in language service

- README.md
- apps/api/src/app/app.controller.ts
- apps/api/src/app/modules/sessions/sessions.service.ts
Fix a bug due to an API change in MongoDB 5.x (but using 4.4)
Introduce in https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/169/
> fix: update pipelines for mongodb 4.4

- apps/api/src/app/core/services/grpc-error.service.ts
- apps/api/src/app/modules/applications/applications.service.ts
- apps/api/src/app/modules/sessions/sessions.service.ts
- apps/api/src/app/modules/tasks/tasks.service.ts
- apps/api/src/main.ts
- apps/app/src/app/core/services/http/error.service.ts
- feat: add a logger for error
- feat: add a logger for error
- feat: set log level
- feat: set log level
> feat: add logger

- apps/app/src/app/pages/pages-routing.module.ts
- apps/app/src/app/pages/pages.component.html
- apps/app/src/app/pages/pages/how-to-use/how-to-use-routing.module.ts
- apps/app/src/app/pages/pages/how-to-use/how-to-use.component.html
- apps/app/src/app/pages/pages/how-to-use/how-to-use.component.ts
- apps/app/src/app/pages/pages/how-to-use/how-to-use.module.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
> feat: create how to use page

- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
fix https://github.com/aneoconsulting/ArmoniK/issues/489
> fix: hide duration when started is not defined

- apps/api/src/app/app.controller.ts
- apps/api/src/app/core/services/grpc-error.service.ts
- apps/api/src/app/modules/sessions/sessions.controller.ts
- apps/api/src/app/modules/tasks/tasks.controller.ts
- apps/app/src/app/pages/pages.component.html
- apps/app/src/app/pages/pages/dashboard/components/applications-errors-list/applications-errors-list.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/pages/task-detail/task-detail.component.html
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.html
- apps/app/src/app/pages/pages/sessions/sessions.component.html
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- package.json
https://github.com/aneoconsulting/ArmoniK/issues/508
> fix: duration in ms and cancellation

- apps/api/src/app/app.controller.ts
- apps/app/src/app/pages/pages.component.html
- package.json
https://github.com/aneoconsulting/ArmoniK/issues/500
> chore: v0.7.0

- apps/app/src/app/pages/pages/sessions/sessions.component.html
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
https://github.com/aneoconsulting/ArmoniK/issues/515
> feat: create actions column for sessions

- apps/app/src/app/pages/pages/sessions/pages/session-detail/components/tasks-list/tasks-list.component.html
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
https://github.com/aneoconsulting/ArmoniK/issues/504
> feat: create actions column for tasks

- apps/app/src/app/pages/pages.component.html
- apps/app/src/app/pages/pages.module.ts
fix https://github.com/aneoconsulting/ArmoniK/issues/607
> feat: add Seq and Grafana links

- README.md
- apps/api/src/app/common/options/mongo-client.options.ts
fix: https://github.com/aneoconsulting/ArmoniK/issues/695
> fix: mongodb connexion

- .github/workflows/cd-docker.yml
- .github/workflows/ci.yaml
- .gitignore
- app.Dockerfile
- apps/app/project.json
- apps/app/src/app/app.component.spec.ts
- apps/app/src/app/core/core.module.ts
- apps/app/src/app/core/services/grpc/grpc-pager.service.ts
- apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
- apps/app/src/app/core/services/grpc/index.ts
- apps/app/src/app/core/services/index.ts
- apps/app/src/app/core/services/settings.service.spec.ts
- apps/app/src/app/core/services/settings.service.ts
- apps/app/src/app/core/types/app-nav-link.ts
- apps/app/src/app/core/types/app-nav-link.type.ts
- apps/app/src/app/core/types/grpc-params.type.ts
- apps/app/src/app/core/types/index.ts
- apps/app/src/app/pages/components/applications-subnav/applications-subnav.component.spec.ts
- apps/app/src/app/pages/pages.component.html
- apps/app/src/app/pages/pages.component.spec.ts
- apps/app/src/app/pages/pages.component.ts
- apps/app/src/app/pages/pages.module.ts
- apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
- apps/app/src/app/pages/pages/sessions-list/sessions-list.component.scss
- apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.spec.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- package.json
fix: https://github.com/aneoconsulting/ArmoniK/issues/634
fix: https://github.com/aneoconsulting/ArmoniK/issues/659
fix: https://github.com/aneoconsulting/ArmoniK/issues/662
fix: https://github.com/aneoconsulting/ArmoniK/issues/666
> feat: fetch sessions using grpc

- apps/app/src/app/core/services/grpc/grpc-sessions.service.ts
- apps/app/src/app/pages/pages/sessions-list/sessions-list.component.html
- apps/app/src/app/pages/pages/sessions-list/sessions-list.component.ts
fix https://github.com/aneoconsulting/ArmoniK/issues/691
> feat: handle timeout in sessions

- apps/app/src/app/core/core.module.ts
- apps/app/src/app/core/services/browser-title.service.spec.ts
- apps/app/src/app/core/services/browser-title.service.ts
- apps/app/src/app/pages/pages/dashboard/dashboard.component.spec.ts
- apps/app/src/app/pages/pages/sessions/pages/session-detail/session-detail.component.spec.ts
fix https://github.com/aneoconsulting/ArmoniK/issues/716
> refactor: browser title service

- .github/workflows/cd-docker.yml
- ci: update docker file
- ci: update docker file
> ci: fix npm installation

- apps/app/tsconfig.editor.json
fix https://github.com/aneoconsulting/ArmoniK/issues/761
> test: fix types for specs files

- apps/app/src/app/pages/results/features/results-list/results-list.module.ts
- apps/app/src/app/pages/results/features/results-list/results-list.page.html
- apps/app/src/app/pages/results/features/results-list/results-list.page.ts
- apps/app/src/app/pages/sessions/features/sessions-list/sessions-list.page.ts
- apps/app/src/app/pages/tasks/features/tasks-list/tasks-list.module.ts
- apps/app/src/app/pages/tasks/features/tasks-list/tasks-list.page.html
- apps/app/src/app/pages/tasks/features/tasks-list/tasks-list.page.ts
fix https://github.com/aneoconsulting/ArmoniK/issues/762
> refactor: auto refresh component in pages

- apps/app/src/app/shared/feature/the-history-navigation/the-history-navigation.component.html
- apps/app/src/app/shared/feature/the-history-navigation/the-history-navigation.component.scss
- apps/app/src/app/shared/feature/the-history-navigation/the-history-navigation.component.ts
- apps/app/src/app/shared/util/services/history.service.spec.ts
- apps/app/src/app/shared/util/services/history.service.ts
fix https://github.com/aneoconsulting/ArmoniK/issues/765
> fix: history

- apps/app/src/app/results/feature/results-list/results-list.page.scss
- apps/app/src/app/sessions/feature/sessions-list/sessions-list.page.scss
- apps/app/src/app/tasks/feature/tasks-list/tasks-list.page.scss
- libs/shared/feature/src/lib/auto-refresh-dropdown/auto-refresh-dropdown.component.html
- libs/shared/feature/src/lib/auto-refresh-dropdown/auto-refresh-dropdown.component.scss
fix https://github.com/aneoconsulting/ArmoniK/issues/774
> fix: auto refresh capitalize

- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
fix https://github.com/aneoconsulting/ArmoniK/issues/772
> fix: remove applications subnav translations

- .husky/commit-msg
- .husky/pre-commit
- package.json
Read the issue below to learn why
fix https://github.com/aneoconsulting/ArmoniK/issues/785
> chore: remove husky

- apps/app/src/app/shared/feature/filters/date-filter/date-filter.component.html
- apps/app/src/app/shared/feature/filters/date-filter/date-filter.component.spec.ts
- apps/app/src/app/shared/feature/filters/date-filter/date-filter.component.ts
- apps/app/src/app/shared/feature/filters/index.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
fix https://github.com/aneoconsulting/ArmoniK/issues/783
> feat: create date filter

- apps/app/src/app/shared/util/services/browser-title.service.spec.ts
- apps/app/src/app/shared/util/services/browser-title.service.ts
fix #https://github.com/aneoconsulting/ArmoniK/issues/791
> fix: title suffix armonik

- angular.json
- apps/app/src/app/app-routing.module.ts
- apps/app/src/app/app.component.ts
- apps/app/src/app/applications/feature/applications-list/applications-list-routing.module.ts
- apps/app/src/app/applications/feature/applications-list/applications-list.module.ts
- apps/app/src/app/applications/feature/applications-list/applications-list.page.html
- apps/app/src/app/applications/feature/applications-list/applications-list.page.scss
- apps/app/src/app/applications/feature/applications-list/applications-list.page.ts
- apps/app/src/app/results/feature/results-list/results-list.page.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- libs/applications/data-access/.eslintrc.json
- libs/applications/data-access/README.md
- libs/applications/data-access/karma.conf.js
- libs/applications/data-access/project.json
- libs/applications/data-access/src/index.ts
- libs/applications/data-access/src/lib/services/grpc-applications.service.spec.ts
- libs/applications/data-access/src/lib/services/grpc-applications.service.ts
- libs/applications/data-access/src/test.ts
- libs/applications/data-access/tsconfig.json
- libs/applications/data-access/tsconfig.lib.json
- libs/applications/data-access/tsconfig.spec.json
- libs/shared/data-access/src/index.ts
- tsconfig.base.json
fix: https://github.com/aneoconsulting/ArmoniK/issues/671
fix: https://github.com/aneoconsulting/ArmoniK/issues/673
fix: https://github.com/aneoconsulting/ArmoniK/issues/674
fix: https://github.com/aneoconsulting/ArmoniK/issues/666
fix https://github.com/aneoconsulting/ArmoniK/issues/691
-  [x] Create the datagrid
> feat: add applications grid

- angular.json
- apps/app/src/app/app-routing.module.ts
- apps/app/src/app/app.component.html
- apps/app/src/app/shared/data-access/auth.service.ts
- apps/app/src/app/users/feature/users-me/users-me-routing.module.ts
- apps/app/src/app/users/feature/users-me/users-me.module.ts
- apps/app/src/app/users/feature/users-me/users-me.page.html
- apps/app/src/app/users/feature/users-me/users-me.page.scss
- apps/app/src/app/users/feature/users-me/users-me.page.ts
- apps/app/src/app/users/feature/users-shell/users-shell-routing.module.ts
- apps/app/src/app/users/feature/users-shell/users-shell.module.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- tsconfig.base.json
fix https://github.com/aneoconsulting/ArmoniK/issues/779
> feat: create a user profile page

- apps/app/src/app/shared/ui/custom-columns-manager/custom-columns-manager.component.html
- apps/app/src/app/shared/ui/custom-columns-manager/custom-columns-manager.component.spec.ts
- apps/app/src/app/shared/ui/custom-columns-manager/custom-columns-manager.component.ts
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
fix https://github.com/aneoconsulting/ArmoniK/issues/792
> feat: create custom columns manager

- README.md
> docs: update readme with project structure

- .github/workflows/deploy-docs.yml
> ci: fix install dependancies

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.md
> chore: fix project name in templates

- .github/workflows/deploy-docs.yml
> ci: add paths to deploy docs

- .github/workflows/ci.yaml
> ci: add immutable to yarn install

- apps/app/src/app/shared/data-access/authorization.service.ts
- apps/app/src/app/tasks/feature/tasks-list/tasks-list.page.html
- apps/app/src/app/tasks/feature/tasks-list/tasks-list.page.ts
> feat: add authorizations to tasks

- libs/tasks/data-access/src/lib/services/grpc-tasks.service.ts
> chore: update armonik api version

- nginx.conf
> fix: remove a line

- .github/workflows/semantic-pull-request.yml
> ci: add semantic pr

- apps/app/src/app/errors/feature/error/error.page.ts
- apps/app/src/locale/messages.en.xlf
- apps/app/src/locale/messages.fr.xlf
- apps/app/src/locale/messages.xlf
fix #426 
Added a `$localize` to the not found response on error page..
> feat: translation for error page

- apps/app/src/app/sessions/feature/sessions-list/sessions-list.page.ts
fix #437  
Changed filter "active" verification
> fix: clear application filter button on session

- apps/app/src/app/app.component.html
- apps/app/src/app/app.component.ts
fix #431 
Applications and partitions are now part of a `tableLinks` navLink table.
> refactor: group partitions with applications

- apps/app/src/app/partitions/feature/partitions-list/partitions-list.page.ts
fix #428 
Partitions `clear` function now reset filters before deleting them.
> fix: partitions-list filters clearing

- apps/app/src/app/results/feature/results-list/results-list.page.ts
fix #443 
Now use `getStatusLabel` to have the labels for statusList.
> fix: statuslist is now localized

- .github/workflows/ci.yaml
- app.Dockerfile
fix #432
From 8 minutes to 5 minutes (can still be improved)
> ci: add cache

- .eslintignore
> fix: eslint ignore api

- .docs/package-lock.json
- .docs/package.json
> chore: update docs dependencies

- .github/workflows/cd-docker.yml
- .github/workflows/ci.yaml
- app.Dockerfile
- apps/app-e2e/src/integration/app.spec.ts
- apps/app/src/environments/environment.prod.ts
> chore: changed path to /old-admin/

- package.json
- yarn.lock
> chore(deps): update

- .github/workflows/deploy-docs.yml
`actions/upload-pages-artifact@v1` does not support the working directory option.
> ci: update deploy-docs

- apps/app/src/app/applications/feature/applications-list/applications-list.page.ts
> fix: clear all filters button now works properly

- apps/app/src/app/shared/util/services/settings.service.ts
Now verify is there is only one param in the url
fix #485
> fix: queryListParams

- apps/app/src/app/sessions/feature/sessions-list/sessions-list.page.ts
> fix: session time filters now retrieve correct value from url

- libs/applications/data-access/src/lib/services/grpc-applications.service.spec.ts
- libs/applications/data-access/src/lib/services/grpc-applications.service.ts
> fix: unset application orderBy in URL

- package.json
- pnpm-lock.yaml
Because of a major update of pnpm, we need to update the lock file too.
> chore: update pnpm

- apps/app/src/locale/messages.fr.xlf
fix #495
Update a poorly translated item.
> fix: update a poor translate in dashboard

- apps/app/src/app/app.component.html
- apps/app/src/app/app.component.scss
- apps/app/src/app/app.component.ts
fix #502
`package.json` is now the single source of truth for the version.
> fix: use package.json version

- apps/app/proxy.conf.json.example
API is no more a component of the GUI. It has been removed several month ago in favor of Core API.
> chore: remove unused endpoints

- app.Dockerfile
https://github.com/aneoconsulting/ArmoniK/issues/1172
Change image base for Admin GUI to use an alpine and not Debian image to run nginx
> fix: CVE issue with Debian LTS

- package.json
Release a new version to use the new image with CVE security fix.
> chore: release 0.9.2

- .docs/package.json
- .docs/pnpm-lock.yaml
Update pnpm version in order to have the new lock file version. This will restore the docs deployment workflow.
> chore: update pnpm version

- package.json
> chore: release v0.9.4

- apps/app/src/app/pages/pages.component.html
- apps/app/src/assets/i18n/en.json
- apps/app/src/assets/i18n/fr.json
- package-lock.json
Add an alert to tell to users that this version is deprecated.
Then, a new version will be created.
> chore: deprecate version 0.8

- app.Dockerfile
- apps/app-e2e/src/integration/app.spec.ts
- apps/app/src/environments/environment.prod.ts
This PR is related to https://github.com/aneoconsulting/ArmoniK.Infra/pull/79
> chore: update admin 0.8 path

- tsconfig.spec.json
Add @angular/localize in order to handle translation in testing.
> fix: add @angular/localize to tsconfig.spec.json

- .github/workflows/ci.yml
- src/app/services/versions.service.spec.ts
uses [jest-coverage-report](https://github.com/marketplace/actions/jest-coverage-report)
The action comments once the PR, and edit the comment at each run
> chore: added test coverage to CI

- src/locale/messages.fr.xlf
- src/locale/messages.xlf
> chore: added missing "property" translation

- src/app/services/table-url.service.ts
> fix: update regex to prevent denial of service

- src/app/dashboard/index.component.spec.ts
> fix: http to https in tests

- src/app/applications/index.component.ts
- src/app/applications/services/applications-index.service.ts
- src/app/components/columns-button.component.ts
- src/app/components/table-actions-toolbar.component.spec.ts
- src/app/components/table-actions-toolbar.component.ts
- src/app/partitions/index.component.ts
- src/app/partitions/services/partitions-index.service.ts
- src/app/results/index.component.ts
- src/app/results/services/results-index.service.ts
- src/app/services/default-config.service.ts
- src/app/services/icons.service.ts
- src/app/services/table.service.spec.ts
- src/app/services/table.service.ts
- src/app/sessions/index.component.ts
- src/app/sessions/services/sessions-index.service.ts
- src/app/tasks/index.component.ts
- src/app/tasks/services/tasks-index.service.spec.ts
- src/app/tasks/services/tasks-index.service.ts
- src/app/types/config.ts
> feat: lock and unlock columns for tables

- src/app/components/columns-modify-dialog.component.ts
> fix: filter disappearing fixed

- src/app/components/auto-refresh-button.component.ts
- src/app/components/auto-refresh-dialog.component.ts
- src/app/components/table-actions-toolbar.component.ts
> feat: autorefresh button enhancement

- src/app/components/auto-refresh-button.component.ts
> feat: feedback added for the chosen refresh interval

- src/app/components/columns-modify-dialog.component.ts
- src/app/services/storage.service.spec.ts
- fixed if statement inside else block
- fixed one cognitive complexity bug
> fix: sonar code syntax

- src/app/components/table/table-inspect-object.component.ts
- src/app/sessions/index.component.ts
- src/app/tasks/index.component.ts
> fix: empty options options field

- src/app/dashboard/components/line.component.ts
- src/app/dashboard/components/statuses-group-card.component.spec.ts
- src/app/dashboard/components/statuses-group-card.component.ts
> feat: dashboard pass applied filter on redirection

- package.json
- pnpm-lock.yaml
- src/app/results/services/results-filters.service.ts
- src/app/results/services/results-grpc.service.ts
- src/app/results/services/results-index.service.ts
In order to have a working code, we need both of the modifications
> chore: update api 3.15.0 and add result size

- src/app/applications/components/table.component.ts
- src/app/components/filters/filters-chips.component.spec.ts
- src/app/components/filters/filters-chips.component.ts
- src/app/components/filters/filters-dialog-and.component.ts
- src/app/components/filters/filters-dialog-filter-field.component.spec.ts
- src/app/components/filters/filters-dialog-filter-field.component.ts
- src/app/components/filters/filters-dialog-or.component.ts
- src/app/components/filters/filters-dialog.component.ts
- src/app/components/filters/filters-toolbar.component.ts
- src/app/dashboard/components/statuses-group-card.component.ts
- src/app/partitions/components/table.component.ts
- src/app/services/utils.service.spec.ts
- src/app/services/utils.service.ts
- src/app/sessions/index.component.ts
- src/app/sessions/services/sessions-grpc.service.ts
- src/app/sessions/types.ts
- src/app/tasks/index.component.ts
- src/app/tasks/services/tasks-filters.service.spec.ts
- src/app/tasks/services/tasks-grpc.service.ts
- src/app/tasks/types.ts
- src/app/types/dialog.ts
- src/app/types/filter-definition.ts
- src/app/types/filters.ts
> feat: generic filtering

- src/app/components/count-tasks-by-status.component.spec.ts
- src/app/components/count-tasks-by-status.component.ts
- src/app/components/view-tasks-by-status.component.spec.ts
- src/app/components/view-tasks-by-status.component.ts
- src/app/partitions/components/table.component.html
- src/app/partitions/components/table.component.ts
- src/app/partitions/types.ts
- src/app/sessions/components/table.component.html
- src/app/sessions/components/table.component.ts
- src/app/types/dialog.ts
This PR improve the situation with this component. There are still some work to do on it but at least the information provided to the user is correct.
> fix: count by status

- src/app/applications/services/applications-filters.service.ts
- src/app/applications/types.ts
- src/app/components/filters/filters-dialog-filter-field.component.spec.ts
- src/app/components/filters/filters-dialog-filter-field.component.ts
- src/app/partitions/services/partitions-filters.service.ts
- src/app/partitions/types.ts
- src/app/results/services/results-filters.service.ts
- src/app/results/types.ts
- src/app/sessions/services/sessions-filters.service.ts
- src/app/sessions/types.ts
- src/app/tasks/services/tasks-filters.service.ts
- src/app/tasks/types.ts
- src/app/types/filter-definition.ts
> fix: filters

- src/app/results/show.component.ts
> fix: result id not showing

- src/app/applications/components/table.component.ts
- src/app/components/table/table-actions.component.html
- src/app/components/table/table-actions.component.ts
- src/app/sessions/components/table.component.html
- src/app/sessions/components/table.component.spec.ts
- src/app/sessions/components/table.component.ts
- src/app/tasks/components/table.component.html
- src/app/tasks/components/table.component.spec.ts
- src/app/tasks/components/table.component.ts
- src/app/types/data.ts
- src/app/types/table.ts
> feat: actions column composant

- src/app/components/filters/filters-dialog-input.component.html
- src/app/components/filters/filters-dialog-input.component.ts
- src/themes.css
> feat: pretty time picker

- src/app/applications/components/table.component.ts
- src/app/partitions/components/table.component.html
- src/app/results/components/table.component.html
- src/app/sessions/components/table.component.html
- src/app/tasks/components/table.component.html
- src/styles.css
> chore: better scrollbar handling in tables

- src/app/tasks/index.component.ts
> feat: select column is now at first position

- src/app/components/table/table-cell.component.ts
> fix: count-tasks-by-status refresh crash

- src/app/sessions/components/table.component.ts
> fix: session id redirection to tasks

- src/styles.css
> fix: disappearing icons in table menus

- src/app/components/show-card-content.component.html
- src/app/components/show-card-content.component.spec.ts
- src/app/components/show-card-content.component.ts
- src/app/components/show-card.component.spec.ts
- src/app/components/show-card.component.ts
- src/app/components/show-page.component.html
- src/app/components/show-page.component.ts
- src/app/partitions/show.component.spec.ts
- src/app/partitions/show.component.ts
- src/app/pipes/duration.pipe.ts
- src/app/results/show.component.spec.ts
- src/app/results/show.component.ts
- src/app/sessions/show.component.spec.ts
- src/app/sessions/show.component.ts
- src/app/tasks/show.component.spec.ts
- src/app/tasks/show.component.ts
- src/app/types/components/show.ts
Used signals to implement the [ChangeDetectionStrategy.OnPush](https://angular.dev/best-practices/skipping-subtrees#using-onpush), a tool which will help us improve performances in the application.
The grpc call is now directly written in the abstract `show` class.
The display problems from `show-card-content` have been adressed. The code of this component has also been reviewed to have a more concise and simple use.
> chore: rework show component code

- src/app/types/components/table.ts
Should speed things up for tables. Still having a high latency on tasks page.
> fix: table cache call on first refresh

- src/app/components/show-card-content.component.html
- src/app/components/show-card-content.component.spec.ts
- src/app/components/show-card-content.component.ts
- src/app/pipes/pretty.pipe.spec.ts
- src/app/pipes/pretty.pipe.ts
Created a pipe that has the role to turn a key more pretty.
closes #1169
> feat: pretty pipe

- src/app/components/inspect-list.component.html
- src/app/components/inspect-list.component.spec.ts
- src/app/components/inspect-list.component.ts
- src/app/types/components/show.ts
Now buttons are used to redirect.
> refactor: inspect list component display

- src/app/types/column.type.ts
Allow to display and handle Inspection data.
> feat: field type

- src/app/components/inspection/field-content.component.html
- src/app/components/inspection/field-content.component.spec.ts
- src/app/components/inspection/field-content.component.ts
- src/app/components/inspection/inspection-object.component.html
- src/app/components/inspection/inspection-object.component.spec.ts
- src/app/components/inspection/inspection-object.component.ts
> feat: inspect data object

- src/app/healthcheck/healthcheck.component.ts
- src/app/partitions/show.component.spec.ts
- src/app/results/show.component.spec.ts
- src/app/sessions/show.component.spec.ts
- src/app/tasks/show.component.spec.ts
- src/app/types/components/show.ts
- src/app/types/components/table.ts
> fix: grpc-error handling

- src/app/types/services/inspectionService.ts
The inspection service is a tool that will be used by the sessions, partitions, tasks and results inspections pages to display the data correctly.
> feat: inspection service

- src/app/partitions/services/partitions-inspection.service.spec.ts
- src/app/partitions/services/partitions-inspection.service.ts
- src/app/partitions/show.component.spec.ts
- src/app/partitions/show.component.ts
- src/app/results/services/results-inspection.service.spec.ts
- src/app/results/services/results-inspection.service.ts
- src/app/results/show.component.spec.ts
- src/app/results/show.component.ts
- src/app/sessions/services/sessions-inspection.service.spec.ts
- src/app/sessions/services/sessions-inspection.service.ts
- src/app/sessions/show.component.spec.ts
- src/app/sessions/show.component.ts
- src/app/tasks/services/tasks-inspection.service.spec.ts
- src/app/tasks/services/tasks-inspection.service.ts
- src/app/tasks/show.component.spec.ts
- src/app/tasks/show.component.ts
- src/app/types/components/show.ts
Inspection Services are used to choose the order in which the data will be displayed in each inspetion page.
> chore: inspection service implementation

- src/app/services/filter.service.spec.ts
- src/app/services/filters.service.ts
- src/app/sessions/show.component.html
- src/app/sessions/show.component.spec.ts
- src/app/sessions/show.component.ts
New data inspection display for sessions
> feat: sessions inspection

- src/app/partitions/services/partitions-inspection.service.spec.ts
- src/app/partitions/services/partitions-inspection.service.ts
- src/app/partitions/show.component.html
- src/app/partitions/show.component.spec.ts
- src/app/partitions/show.component.ts
New data display for partitions
> feat: partitions inspection

- src/app/tasks/show.component.html
- src/app/tasks/show.component.spec.ts
- src/app/tasks/show.component.ts
> feat: tasks inspection

- src/app/results/show.component.html
- src/app/results/show.component.spec.ts
- src/app/results/show.component.ts
> feat: results inspection

- src/app/components/inspect-list.component.html
- src/app/components/inspect-list.component.spec.ts
- src/app/components/inspect-list.component.ts
- src/app/components/inspection/inspection-list-grid.component.html
- src/app/components/inspection/inspection-list-grid.component.spec.ts
- src/app/components/inspection/inspection-list-grid.component.ts
- src/app/components/show-page.component.html
- src/app/partitions/services/partitions-inspection.service.ts
- src/app/sessions/services/sessions-inspection.service.ts
- src/app/tasks/services/tasks-inspection.service.ts
- src/app/types/column.type.ts
> feat: see all button for inspection lists

- src/app/dashboard/components/lines/task-by-status-line.component.html
- src/app/dashboard/components/lines/task-by-status-line.component.spec.ts
- src/app/dashboard/components/lines/task-by-status-line.component.ts
The error was not creating any issue for the user, but now the code is more compliant to the recent changes with signal handling
> fix: task by status line error on load
