aneoconsulting/ArmoniK.Admin.GUI

apps/app-e2e/cypress.json

Sometimes, DOM will take more time than expected to load which result in a failure of e2e tests. But after a job restart, tests pass !

ci: update timeout for cypress

---

apps/app/src/app/pages/pages.component.html
apps/app/src/app/pages/pages.component.ts

With a `/` at the beginning, the base Url was not used (so `/admin` was not used in production)

fix: update path for armonik logo

---

.github/workflows/cd-docker.yml
.github/workflows/ci.yaml

The new pipeline allow us to build and push images because they won't be created and pushed if tests fails.
This will allow us to use pr image on dev environment

ci: push images from pr

---

.github/workflows/cd-docker.yml
.github/workflows/ci.yaml

ci: use cache for proto files

---

apps/app/src/app/results/feature/results-list/results-list.page.ts
apps/app/src/app/shared/feature/filters/combobox-filter/combobox-filter.component.ts
apps/app/src/app/shared/feature/filters/date-filter/date-filter.component.ts
apps/app/src/app/shared/feature/filters/id-filter/id-filter.component.ts
apps/app/src/app/shared/feature/filters/numeric-filter/numeric-filter.component.ts
apps/app/src/app/shared/feature/filters/select-filter/select-filter.component.ts
apps/app/src/app/tasks/feature/tasks-list/tasks-list.page.ts

fix #416 
Created `reset` function for each filter. These functions clear the filter without emitting any event.
Datagrid `clearAllFilters` functions call at first the `reset` function for every active filter, and then destroy the filters.

fix: clearing all filters now set each filter unactive

---

renovate.json

Group slug is used to group packages. In our case, we want to split package rules in different groups.

chore: fix group slug in renovate config

---

app.Dockerfile

Update the version of the docker image base from nginx:1.25.1-alpine3.17 to nginx:1.25.2-alpine3.18-slim to fix CVE.

chore: update docker image base

---

src/app/dashboard/components/statuses-group-card.component.ts

#769 
Now redirecting on the Tasks page when clicking on a statuses group name on the dashboard

feat: dashboard statuses group redirect

---

src/app/pipes/duration.pipe.ts

In tasks table, durations have been switched to milliseconds. 
Fixes #767

feat: duration time from nano to ms

---

src/app/components/view-tasks-by-status-dialog.component.spec.ts
src/app/components/view-tasks-by-status.component.spec.ts
src/app/dashboard/components/manage-groups-dialog.component.spec.ts
src/app/dashboard/components/statuses-group-card.component.spec.ts
src/app/dashboard/services/dashboard-index.service.spec.ts
src/app/tasks/services/tasks-filters.service.spec.ts
src/app/tasks/services/tasks-statuses.service.ts

- Replaced the "finished" status name by "completed" which was more relevant and less ambiguous in the dashboard statuses group `Finished` and also in the available statuses filter on the tasks page
- Updated the corresponding tests

fix: replace finished status name by completed on dashboard & filters

---

src/app/components/count-tasks-by-status.component.ts

Cette petite modification permet d'avoir une meilleure lecture des valeurs count task pendant le refresh

fix: count task display

---

src/app/tasks/services/tasks-index.service.ts

chore: update pod ttl display in task table

---

src/app/components/show-action-area.component.html
src/app/components/show-actions.component.ts
src/app/services/icons.service.ts
src/app/sessions/components/table.component.ts
src/app/sessions/index.component.html
src/app/sessions/index.component.ts
src/app/sessions/services/sessions-grpc.service.ts
src/app/sessions/services/sessions-statuses.service.ts
src/app/sessions/show.component.ts
src/app/types/components/show.ts

fix #981 
Hey, 
This PR add the ability to pause and resume a session from the table and the show page.
I also refactor the bouncer for the session to have a single source of truth for capabilities between the table and the show page.

feat(sessions): support pause and resume

---

src/app/app.config.ts
src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts
src/app/settings/index.component.ts

What's new ?
Now, when exporting the GUI configuration, the json will contain a `version` key, with the deployed version of the GUI.
This key is now ***required*** for the GUI to import a configuration, either if it comes from the user or from the server.
To be accepted, a configuration must have a key with the same `major` and `minor` versions.

feat: versions for gui configuration

---

src/app/settings/component/clear-all-dialog.component.html
src/app/settings/component/clear-all-dialog.component.ts
src/app/settings/index.component.html
src/app/settings/index.component.ts

The buttons for the sidebar configuration are located on the top of the editable sidebar and are displayed in a more logical order.
The `add a status` button has been renamed as `add an item` and is bigger.
The `Reset to default` button now use the `clear all` dialog.
The buttons now have a more logical order. 
The buttons are disabled when nothing is selected.
The `Reset` button has been renamed to `Reset Selection`.
The `Clear All` button now use the `clear all` dialog.

feat: settings ux improvements

---

src/app/applications/components/table.component.ts
src/app/applications/services/applications-grpc.service.spec.ts
src/app/applications/services/applications-grpc.service.ts
src/app/dashboard/types.ts
src/app/partitions/components/table.component.ts
src/app/partitions/services/partitions-grpc.service.spec.ts
src/app/partitions/services/partitions-grpc.service.ts
src/app/partitions/show.component.ts
src/app/results/components/table.component.ts
src/app/results/services/results-grpc.service.spec.ts
src/app/results/services/results-grpc.service.ts
src/app/results/show.component.ts
src/app/services/grpc-sort-field.service.spec.ts
src/app/services/grpc-sort-field.service.ts
src/app/services/utils.service.spec.ts
src/app/services/utils.service.ts
src/app/sessions/components/table.component.ts
src/app/sessions/services/sessions-grpc.service.spec.ts
src/app/sessions/services/sessions-grpc.service.ts
src/app/sessions/show.component.ts
src/app/tasks/components/table.component.ts
src/app/tasks/services/tasks-grpc.service.spec.ts
src/app/tasks/services/tasks-grpc.service.ts
src/app/tasks/show.component.ts
src/app/types/components/show.ts
src/app/types/components/table.ts
src/app/types/services.ts
src/app/types/services/grpcService.ts

The GrpcTableClass is an abstraction of the grpc services that list data for tables. It gives a simple way to referenciate it, and allows a developper to only build few functions and let the abstraction do the rest.
A lot of code had to be edited in order to make it compatible.

feat: grpcTableClass

---

src/app/components/count-tasks-by-status.component.spec.ts
src/app/components/count-tasks-by-status.component.ts
src/app/components/table/table-cell.component.html

The component use a `refresh` subject that is "piped" to fetch the data.
Before, it was initiated when a `TaskSummaryFilter` was passed to the component. But since the filters are updated every time we get new data, the initialisation was remade, adding a new fetch instruction to the already existing one.

fix: linear increase of count by status refresh

---

src/app/components/statuses/form-statuses-group.component.html
src/app/components/statuses/form-statuses-group.component.spec.ts
src/app/components/statuses/form-statuses-group.component.ts
src/app/components/statuses/manage-groups-dialog.component.spec.ts
src/app/components/statuses/manage-groups-dialog.component.ts

When creating a new group of tasks status for sessions, partitions and applications, selecting the first status will give its name to the group.
Also refactored the group creation form.

feat: tasks by status auto name

---

src/app/components/inspection/inspection-object.component.html
src/app/components/inspection/inspection-object.component.spec.ts
src/app/components/inspection/inspection-object.component.ts
src/app/components/inspection/message.component.css
src/app/components/inspection/message.component.html
src/app/components/inspection/message.component.spec.ts
src/app/components/inspection/message.component.ts
src/app/results/services/results-inspection.service.ts
src/app/tasks/services/tasks-inspection.service.ts
src/app/types/column.type.ts
src/app/types/data.ts
src/inspections.css

New behaviour: the messages objects, such as `Output` and `Status Message`, inside a `TaskRaw` object, will be displayed only if their message is not empty.
The display will be as follow:

chore(ux): messages display in inspection page

---

src/app/services/filters-cache.service.spec.ts
src/app/services/filters-cache.service.ts
src/app/settings/index.component.html
src/app/settings/index.component.ts

Button can now be disabled if no cached are stored. Null and undefined values are also counted as cached data (in case there are bugs introduced by null and undefined values).

chore: filter cache better understanding

---

package.json
pnpm-lock.yaml
src/app/components/filters/filters-chips.component.spec.ts
src/app/components/filters/filters-chips.component.ts
src/app/components/filters/filters-dialog-input.component.css
src/app/components/filters/filters-dialog-input.component.html
src/app/components/filters/filters-dialog-input.component.spec.ts
src/app/components/filters/filters-dialog-input.component.ts

The previous DateTime picker was no longer supporting newer versions of Angular and was not maintained anymore.
The new DateTime picker is a fork from the previous one, using newer angular tools, and supports almost every angular version.
Plus it fix some css issues from the previous picker !
Before:
After:

chore: new date time picker

---

src/app/components/table/table.component.ts

The "Cancel Tasks" button stayed disabled even when tasks were selected in the tasks table.

fix: add selectionChange event binding to tasks table
